import { mutation } from "./_generated/server";

export const seedAll = mutation({
  handler: async (ctx) => {
    // Clear existing tools
    const existing = await ctx.db.query("tools").collect();
    for (const tool of existing) {
      await ctx.db.delete(tool._id);
    }
    
    const tools = [
      // === AI SERVICES ===
      {
        name: "OpenAI",
        type: "api",
        category: "AI",
        description: "GPT models, DALL-E image generation, embeddings",
        accessMethod: "API Key",
        capabilities: ["Text generation", "Image generation", "Code assistance", "Embeddings"],
        status: "active",
        icon: "🤖",
        url: "https://platform.openai.com",
      },
      {
        name: "Anthropic",
        type: "api",
        category: "AI",
        description: "Claude models for reasoning and analysis",
        accessMethod: "API Key",
        capabilities: ["Text generation", "Analysis", "Coding", "Research"],
        status: "active",
        icon: "🧠",
        url: "https://console.anthropic.com",
      },
      {
        name: "ElevenLabs",
        type: "api",
        category: "AI",
        description: "Text-to-speech and voice cloning",
        accessMethod: "API Key",
        capabilities: ["Text-to-speech", "Voice cloning", "Audio generation"],
        status: "active",
        icon: "🎙️",
        url: "https://elevenlabs.io",
      },
      {
        name: "Gemini",
        type: "api",
        category: "AI",
        description: "Google's AI for embeddings and image generation",
        accessMethod: "API Key",
        capabilities: ["Embeddings", "Image generation", "Memory search"],
        status: "active",
        icon: "💎",
        url: "https://ai.google.dev",
      },
      
      // === FINANCE ===
      {
        name: "Schwab",
        type: "api",
        category: "Finance",
        description: "Trading account access, positions, orders",
        accessMethod: "OAuth",
        capabilities: ["View positions", "Account balances", "Order history", "Market data"],
        status: "active",
        icon: "📈",
        url: "https://developer.schwab.com",
      },
      {
        name: "Alpha Vantage",
        type: "api",
        category: "Finance",
        description: "Stock market data and fundamentals",
        accessMethod: "API Key",
        capabilities: ["Stock quotes", "Historical data", "Fundamentals", "Technical indicators"],
        status: "active",
        icon: "📊",
        url: "https://alphavantage.co",
      },
      
      // === COMMUNICATION ===
      {
        name: "Discord",
        type: "api",
        category: "Communication",
        description: "Discord bot for messaging and server management",
        accessMethod: "Bot Token",
        capabilities: ["Send messages", "Read messages", "Manage channels", "Reactions", "Embeds"],
        status: "active",
        icon: "💬",
        url: "https://discord.com",
      },
      {
        name: "Telegram",
        type: "api",
        category: "Communication",
        description: "Telegram bot for messaging",
        accessMethod: "Bot Token",
        capabilities: ["Send messages", "Read messages", "Inline keyboards", "File sharing"],
        status: "active",
        icon: "✈️",
        url: "https://telegram.org",
      },
      {
        name: "AgentMail",
        type: "api",
        category: "Communication",
        description: "Email service for AI agents",
        accessMethod: "API Key",
        capabilities: ["Send emails", "Receive emails", "Email management"],
        status: "active",
        icon: "📧",
        url: "https://agentmail.to",
        notes: "Primary email: alfred-x@agentmail.to",
      },
      {
        name: "Proton Mail",
        type: "account",
        category: "Communication",
        description: "Secure backup email account",
        accessMethod: "Browser",
        capabilities: ["Email backup", "Secure communication"],
        status: "active",
        icon: "🔐",
        url: "https://proton.me",
        notes: "Backup: alfred.work.1@proton.me",
      },
      
      // === DEVELOPMENT ===
      {
        name: "GitHub",
        type: "api",
        category: "Development",
        description: "Code hosting, PRs, issues, Actions",
        accessMethod: "CLI + OAuth",
        capabilities: ["Create repos", "Manage PRs", "Issues", "Actions", "Code search"],
        status: "active",
        icon: "🐙",
        url: "https://github.com",
      },
      {
        name: "Vercel",
        type: "api",
        category: "Development",
        description: "Deployment and hosting platform",
        accessMethod: "Token",
        capabilities: ["Deploy apps", "Manage domains", "View logs", "Environment vars"],
        status: "active",
        icon: "▲",
        url: "https://vercel.com",
      },
      {
        name: "Convex",
        type: "api",
        category: "Development",
        description: "Real-time database and backend",
        accessMethod: "API Key",
        capabilities: ["Database CRUD", "Real-time sync", "Scheduled functions", "File storage"],
        status: "active",
        icon: "⚡",
        url: "https://convex.dev",
      },
      
      // === SEARCH & WEB ===
      {
        name: "Brave Search",
        type: "api",
        category: "Search",
        description: "Web search API",
        accessMethod: "API Key",
        capabilities: ["Web search", "News search", "Image search"],
        status: "active",
        icon: "🔍",
        url: "https://brave.com/search/api",
      },
      {
        name: "Browser Automation",
        type: "skill",
        category: "Search",
        description: "Control web browser for automation",
        accessMethod: "Clawdbot",
        capabilities: ["Navigate pages", "Fill forms", "Take screenshots", "Extract data", "Click elements"],
        status: "active",
        icon: "🌐",
      },
      
      // === SOCIAL ===
      {
        name: "Twitter/X",
        type: "api",
        category: "Social",
        description: "Twitter API (read-only)",
        accessMethod: "OAuth",
        capabilities: ["Search tweets", "Read mentions", "User lookup"],
        status: "active",
        icon: "🐦",
        url: "https://twitter.com",
        notes: "Read-only access, cannot post",
      },
      
      // === HEALTH ===
      {
        name: "Oura Ring",
        type: "api",
        category: "Health",
        description: "Sleep, activity, and health data",
        accessMethod: "API Key",
        capabilities: ["Sleep data", "Activity data", "Readiness score", "HRV", "Heart rate"],
        status: "active",
        icon: "💍",
        url: "https://cloud.ouraring.com",
      },
      
      // === PRODUCTIVITY ===
      {
        name: "Google Workspace",
        type: "skill",
        category: "Productivity",
        description: "Gmail, Calendar, Drive, Sheets, Docs",
        accessMethod: "OAuth",
        capabilities: ["Read/send email", "Calendar events", "Drive files", "Sheets", "Docs"],
        status: "active",
        icon: "📅",
        url: "https://workspace.google.com",
      },
      {
        name: "Apple Notes",
        type: "skill",
        category: "Productivity",
        description: "Create and manage Apple Notes via memo CLI",
        accessMethod: "CLI",
        capabilities: ["Create notes", "List notes", "Search notes", "Edit notes"],
        status: "active",
        icon: "📝",
      },
      {
        name: "Notion",
        type: "skill",
        category: "Productivity",
        description: "Notion pages, databases, and blocks",
        accessMethod: "API Key",
        capabilities: ["Create pages", "Manage databases", "Search", "Update blocks"],
        status: "active",
        icon: "📓",
        url: "https://notion.so",
      },
      {
        name: "Slack",
        type: "skill",
        category: "Productivity",
        description: "Slack messaging and workspace management",
        accessMethod: "Bot Token",
        capabilities: ["Send messages", "Read channels", "Reactions", "File sharing"],
        status: "active",
        icon: "💼",
        url: "https://slack.com",
      },
      
      // === CLI TOOLS ===
      {
        name: "ffmpeg",
        type: "cli",
        category: "Media",
        description: "Video and audio processing",
        accessMethod: "CLI",
        capabilities: ["Convert video", "Extract audio", "Trim clips", "Extract frames", "Compress"],
        status: "active",
        icon: "🎬",
      },
      {
        name: "QMD",
        type: "cli",
        category: "Search",
        description: "Local markdown vector search",
        accessMethod: "CLI",
        capabilities: ["Semantic search", "BM25 search", "Hybrid search", "Index markdown"],
        status: "active",
        icon: "🔎",
      },
      {
        name: "gh CLI",
        type: "cli",
        category: "Development",
        description: "GitHub command line interface",
        accessMethod: "CLI",
        capabilities: ["Create PRs", "Manage issues", "View runs", "API queries"],
        status: "active",
        icon: "⌨️",
      },
      
      // === WEB SERVICES (Browser Access) ===
      {
        name: "Marriott",
        type: "web",
        category: "Travel",
        description: "Hotel booking and MMP rate checking",
        accessMethod: "Browser",
        capabilities: ["Search rates", "Check MMP prices", "View availability"],
        status: "active",
        icon: "🏨",
        url: "https://marriott.com",
      },
      {
        name: "Apple ID",
        type: "account",
        category: "Account",
        description: "Apple account for App Store and iCloud",
        accessMethod: "Browser",
        capabilities: ["App Store", "iCloud access", "Apple services"],
        status: "active",
        icon: "🍎",
        url: "https://apple.com",
        notes: "Account: alfred-x@agentmail.to",
      },
      
      // === UTILITIES ===
      {
        name: "Weather",
        type: "skill",
        category: "Utilities",
        description: "Current weather and forecasts",
        accessMethod: "Clawdbot",
        capabilities: ["Current weather", "Forecasts", "Multiple locations"],
        status: "active",
        icon: "🌤️",
      },
      {
        name: "Web Fetch",
        type: "skill",
        category: "Utilities",
        description: "Fetch and extract content from URLs",
        accessMethod: "Clawdbot",
        capabilities: ["Fetch pages", "Extract text", "Convert to markdown"],
        status: "active",
        icon: "📥",
      },
      {
        name: "Image Analysis",
        type: "skill",
        category: "AI",
        description: "Analyze images with vision models",
        accessMethod: "Clawdbot",
        capabilities: ["Describe images", "Extract text", "Identify objects"],
        status: "active",
        icon: "👁️",
      },
      {
        name: "TTS",
        type: "skill",
        category: "AI",
        description: "Text-to-speech generation",
        accessMethod: "Clawdbot",
        capabilities: ["Convert text to audio", "Multiple voices"],
        status: "active",
        icon: "🔊",
      },
    ];
    
    // Insert all tools
    for (const tool of tools) {
      await ctx.db.insert("tools", {
        ...tool,
        addedAt: Date.now(),
      });
    }
    
    return { inserted: tools.length };
  },
});
